### ISSUE TITLE
Failure when asset doesn't exist

### ISSUE THREAD

**Issue by richardklein** [tenable/integration-asc#1]
The script stops working the moment azure resources are deleted. The resources in tenable.io are not in sync with the resources in azure. Can it be made in such a way that it doesn't break the moment the resource is missing? Perhaps only submit the data when the last seen is less than the interval that is set in the cloud connector.

INFO:tenable_asc.transform.Tio2ASC:querying Tenable.io for the asset records.
INFO:tenable_asc.transform.Tio2ASC:discovered 2 Azure Assets
INFO:tenable_asc.transform.Tio2ASC:querying Tenable.io for vulnerability records                                                                                 .
INFO:tenable_asc.transform.Tio2ASC:processed 237 vulnerabilities out of 237 tota                                                                                 l.
ERROR:restfly.errors.NotFoundError:[404: PUT] https://management.azure.com/subscriptions/xxxxxxxx/resourcegroups/xxxx/providers/microsoft.compute/virtualmachines/serverscan1/providers/Microsoft.Security/assessments/xxxxxx?api-version=2019-01-01-preview body=b'{"error":{"code":"ResourceNotFound","message":"The Resource \'microsoft.compute/virtualMachines/serverscan1\' under resource group \'myrg01\' was not found."}}'
Traceback (most recent call last):
  File "/usr/bin/tenable-asc", line 9, in <module>
    load_entry_point('tenable-microsoft-asc==1.0.0', 'console_scripts', 'tenable-asc')()
  File "/usr/lib/python3.4/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/tenable_asc/cli.py", line 85, in cli
    ingest.ingest(batch_size)
  File "/usr/lib/python3.4/site-packages/tenable_asc/transform.py", line 149, in ingest
    self._upsert_metadata(asset, unhealthy_thresh)
  File "/usr/lib/python3.4/site-packages/tenable_asc/transform.py", line 91, in _upsert_metadata
    '/{}/overview'.format(asset_uuid)
  File "/usr/lib/python3.4/site-packages/tenable_asc/asc/assessments.py", line 48, in create_assessment_finding
    'additionalData': data,
  File "/usr/lib/python3.4/site-packages/restfly/session.py", line 447, in put
    return self._request('PUT', path, **kwargs)
  File "/usr/lib/python3.4/site-packages/restfly/session.py", line 373, in _request
    raise err(resp, retries=retries)
restfly.errors.NotFoundError: [404: PUT] https://management.azure.com/subscriptions/xxxxx/resourcegroups/xxxxx/providers/microsoft.compute/virtualmachines/serverscan1/providers/Microsoft.Security/assessments/xxxxxxx?api-version=2019-01-01-preview body=b'{"error":{"code":"ResourceNotFound","message":"The Resource \'microsoft.compute/virtualMachines/serverscan1\' under resource group \'myrg01\' was not found."}}'

**Comment by SteveMcGrath** [comment]
can you download the latest and test to see if this resolves?

**Comment by richardklein** [comment]
Great, it is resolved ;)
